# Generated by Django 4.2.6 on 2023-10-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmecyinfo', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.IntegerField(unique=True)),
                ('mname', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmecyinfo.dealerinfo')),
            ],
        ),
    ]
