# Generated by Django 4.2.6 on 2023-10-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmecyinfo', '0007_medicineinfo_delete_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinfo',
            name='dname',
            field=models.CharField(max_length=15),
        ),
    ]
