# Generated by Django 4.2.6 on 2023-10-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmecyinfo', '0008_alter_medicineinfo_dname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phone_number', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('quanttity', models.IntegerField()),
                ('total', models.BigIntegerField()),
            ],
        ),
    ]
