# Generated by Django 4.2.6 on 2023-10-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmecyinfo', '0009_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='quanttity',
            new_name='quantity',
        ),
    ]
