# Generated by Django 4.2.7 on 2023-11-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmecyinfo', '0011_alter_purchase_phone_number_alter_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinfo',
            name='dname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmecyinfo.dealerinfo'),
        ),
    ]
